### ISSUE TITLE
FireProfiles throws java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Sceinox** [TRG-Development/ArmA3-ATragMX#17]
```
Caused by: java.lang.NullPointerException: Attempt to read from null array
        at sceinox.atragmx.FireProfiles$Profile.setGun(FireProfiles.java:287)
        at sceinox.atragmx.FireProfiles$Profile.<init>(FireProfiles.java:103)
        at sceinox.atragmx.FireProfiles.<clinit>(FireProfiles.java:6)
```

Happens when calling 
```
FireProfiles.setSelectedProfileToA();
```

and many other methods

**Comment by Sceinox** [comment]
thanks for fixing the typos I made with "drunken programming"
